export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ADD_PAGE_ERROR = "ADD_PAGE_ERROR";
export const LOADING = "LOADING";
export const GET_ACCOUNT_BY_ID = "GET_ACCOUNT_BY_ID";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
